sisense_columns = [
    "Job Number",
    "Sum of 'Revenue'",
    "Year",
    "Period #",
    "Job Number +",
    "Child Acct #",
    "Inches",
    "Ad Type",
    "Section",
    "Class Code",
    "WoRev Bill Cycle",
    "Child Acct Name",
    "First Issue Date",
    "Full Name LF",
    "Commission Rep",
    "MSP/non-MSP",
    "Business Unit GL",
    "GL_LOB_L1",
    "Pub",
    "Revenue",
    "Count of matches",
    "Verified Strategic",
    "Welcome Back",
    "Renewal",
    "Revenue Date",
    "Wave2 Prior Bill",
]

raw_column_types = [
    {"Year": int},
    {"Period #": int},
    {"Job Number": int},
    {"Child Acct #": str},
    {"Inches": float},
    {"Ad Type": str},
    {"Section": str},
    {"Class Code": str},
    {"WoRev Bill Cycle": str},
    {"Child Acct Name": str},
    {"First Issue Date": "datetime64[ns]"},
    {"Full Name LF": str},
    {"Business Unit GL": str},
    {"GL_LOB_L1": str},
    {"Pub": str},
    {"Revenue": float},
]